{
 "title": "1)  Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "name",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "현재 시간", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "온도 (master server)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{id=\"3\"}",
     "legendFormat": "Peripheral Temp"
    }
   ]
  },
  {
   "title": "온도 변화 (master server)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{id=\"3\"}",
     "legendFormat": "Temp"
    }
   ]
  },
  { "title": "공지사항", "type": "text", "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 }, "options": { "content": " - test." } },
  {
   "title": "연락처",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "options": {
    "content": "##### === 관리자 ===\n\n##### === 유지보수 업체 ===\n(주)다산데이타  \n02-871-9932  \ndasan_as@dasandata.co.kr  "
   }
  },
  {
   "title": "Link",
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "[구글](http://google.com)\n\n[User Guide for OpenHPC Cluster](https://github.com/dasandata/Open_HPC/tree/master/Document/User%20Guide)\n\n"
   }
  },
  {
   "title": "master & login node CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "cpu core" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"10.1.1.254:9100\"}",
     "legendFormat": "master cpu (96)"
    }
   ]
  },
  {
   "title": "master Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"10.1.1.254:9100\",job=~\"$job\",device!~'rootfs',device !~'tmpfs',device!~'by-uuid',mountpoint!~\"/boot\",mountpoint!~\"/boot/efi\"} * 100) / node_filesystem_size_bytes{instance=~\"10.1.1.254:9100\",job=~\"$job\",device!~'rootfs',device !~'tmpfs',device!~'by-uuid',mountpoint!~\"/boot\",mountpoint!~\"/boot/efi\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Nodes Status (Total 1)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_nodes_down + slurm_nodes_drain",
     "legendFormat": "Down,Drain"
    },
    {
     "expr": "slurm_nodes_maint + slurm_nodes_resv",
     "legendFormat": "Maint, Reserv"
    },
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_comp",
     "legendFormat": "Allocated"
    },
    { "expr": "slurm_nodes_mix", "legendFormat": "Mixed" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "Fail/Down/Drain/Err Nodes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_nodes_down", "legendFormat": "Down" },
    { "expr": "slurm_nodes_drain", "legendFormat": "Drain" },
    { "expr": "slurm_nodes_err != 0", "legendFormat": "Nodes in *error* state" },
    { "expr": "slurm_nodes_fail != 0", "legendFormat": "Nodes in *fail* state" }
   ]
  },
  {
   "title": "RUNNING/PEND Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_running", "legendFormat": "Running Jobs" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending Jobs" }
   ]
  },
  {
   "title": "실시간 GPU 사용량 (All nodes)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"10.1.1.*:9400\"}",
     "legendFormat": "."
    },
    {}
   ]
  },
  {
   "title": "gpu 사용률 (All nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"10.1.1.*:9400\"})",
     "legendFormat": "GPU Utilization"
    }
   ]
  },
  {
   "title": "실시간 CPU 사용량 (All nodes)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\",note=\"compute-node\"}[1m])) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU 사용률 (All nodes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"10.1.1.*:9100\",note=\"compute-node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Busy Avg"
    }
   ]
  },
  {
   "title": "실시간 Memory 사용량 (All nodes)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"10.1.1.*:9100\",note=\"compute-node\"} / (node_memory_MemTotal_bytes{instance=~\"10.1.1.*:9100\",note=\"compute-node\"})))* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory 사용률 (All nodes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(1 - (node_memory_MemAvailable_bytes{instance=~\"10.1.1.*:9100\",note=\"compute-node\"} / (node_memory_MemTotal_bytes{instance=~\"10.1.1.*:9100\",note=\"compute-node\"})))* 100",
     "legendFormat": "Used Memory"
    }
   ]
  }
 ]
}