### /etc/prometheus/prometheus.yml

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'slurm-exporter'
    scrape_interval:  5s
    scrape_timeout:   5s
    static_configs:
      - targets: ['10.1.1.254:9800']

  - job_name: 'ipmi-exporter'
    scrape_interval:  5s
    scrape_timeout:   5s
    static_configs:
      - targets: ['10.1.1.254:9290']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['10.1.1.254:9100']
          labels:
            note: 'master-node'
    - targets: ['10.1.1.1:9100','10.1.1.2:9100','10.1.1.3:9100','10.1.1.4:9100','10.1.1.5:9100','10.1.1.6:9100','10.1.1.7:9100','10.1.1.8:9100','10.1.1.9:9100','10.1.1.10:9100']
      labels:
        note: 'compute-node'
    - targets: ['10.1.1.11:9100','10.1.1.12:9100','10.1.1.13:9100','10.1.1.14:9100','10.1.1.15:9100','10.1.1.16:9100','10.1.1.17:9100','10.1.1.18:9100','10.1.1.19:9100','10.1.1.20:9100']
      labels:
        note: 'compute-node'
    - targets: ['10.1.1.21:9100','10.1.1.22:9100','10.1.1.23:9100','10.1.1.24:9100','10.1.1.25:9100','10.1.1.26:9100','10.1.1.27:9100','10.1.1.28:9100','10.1.1.29:9100','10.1.1.30:9100']
      labels:
        note: 'compute-node'
    - targets: ['10.1.1.31:9100','10.1.1.32:9100','10.1.1.33:9100']
      labels:
        note: 'compute-node'

  - job_name: 'dcgm-exporter'
    static_configs:
    - targets: ['10.1.1.1:9400','10.1.1.2:9400','10.1.1.3:9400','10.1.1.4:9400','10.1.1.5:9400','10.1.1.6:9400','10.1.1.7:9400','10.1.1.8:9400','10.1.1.9:9400','10.1.1.10:9400']
      labels:
        note: 'compute-node'
    - targets: ['10.1.1.11:9400','10.1.1.12:9400','10.1.1.13:9400','10.1.1.14:9400','10.1.1.15:9400','10.1.1.16:9400','10.1.1.17:9400','10.1.1.18:9400','10.1.1.19:9400','10.1.1.20:9400']
      labels:
        note: 'compute-node'
    - targets: ['10.1.1.21:9400','10.1.1.22:9400','10.1.1.23:9400','10.1.1.24:9400','10.1.1.25:9400','10.1.1.26:9400','10.1.1.27:9400','10.1.1.28:9400','10.1.1.29:9400','10.1.1.30:9400']
      labels:
        note: 'compute-node'
    - targets: ['10.1.1.31:9400','10.1.1.32:9400','10.1.1.33:9400']
      labels:
        note: 'compute-node'
